approval_policy = "on-failure"
model = "gpt-5.2-codex"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
	network_access = true

[features]
	web_search_request = true


[notice]
	"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
