approval_policy = "on-failure"
model = "gpt-5-codex"
sandbox_mode = "workspace-write"
tui = { theme = { name = "dark-charcoal-rainbow" } }

[sandbox_workspace_write]
	network_access = true

[tools]
	web_search = true

[mcp_servers.serena]
	command = "uvx"
	args = [
		"--from",
		"git+https://github.com/oraios/serena",
		"serena",
		"start-mcp-server",
		"--context",
		"codex",
	]
